backend:
  name: github
  repo: Dogson/musical-juice

media_folder: static/assets/images
public_folder: assets/images
logo_url: https://www.campusfrancosenegalais.org/assets/images/logoCFS.png
site_url: https://musical-juice.netlify.app
display_url: Musical Juice

slug:
  encoding: ascii
  clean_accents: true

collections:
  #  MIXES
  - name: mixes
    label: Mixes
    editor:
      preview: false
    folder: src/content/mixes
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - { name: "type", widget: "hidden", label: "Type", default: "mixes" }
      - { name: name, label: Nom du mix }
      - { name: url, label: Lien YouTube, widget: string }